# Generated by Django 3.1.2 on 2020-12-21 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('luggage', models.CharField(max_length=10)),
                ('num_people', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('Late_fee', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='dl_num',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=10)),
                ('availability', models.CharField(max_length=5)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.category')),
                ('loc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.address')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(default=datetime.datetime.today)),
                ('ret_date', models.DateTimeField(default=datetime.datetime.today)),
                ('amt', models.IntegerField()),
                ('status', models.IntegerField()),
                ('act_ret_date', models.DateTimeField(auto_now_add=True)),
                ('dl_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
                ('drop_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop', to='webapp.address')),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='webapp.address')),
                ('reg_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.car')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('bill_status', models.IntegerField()),
                ('late_fee', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.booking')),
            ],
            options={
                'db_table': 'billing',
            },
        ),
    ]
