# Generated by Django 3.1.2 on 2020-12-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201221_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
