# Generated by Django 3.1.2 on 2020-12-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phno',
        ),
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.IntegerField(max_length=5),
        ),
    ]
