# Generated by Django 3.1.2 on 2020-12-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201221_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Late_fee',
            new_name='late_fee',
        ),
        migrations.RemoveField(
            model_name='car',
            name='loc_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop', to='webapp.address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup', to='webapp.address'),
        ),
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reg_num', 'dl_num')},
        ),
    ]
