# Generated by Django 3.1.2 on 2020-12-21 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201222_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='act_ret_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ret_date',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
    ]
