# Generated by Django 3.1.2 on 2020-12-21 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201222_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='act_ret_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ret_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
