# Generated by Django 3.1.2 on 2020-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20201222_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='act_ret_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
