# Generated by Django 3.1.2 on 2021-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210102_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
