# Generated by Django 3.1.2 on 2021-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210107_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirm',
            field=models.IntegerField(default=0),
        ),
    ]
