# Generated by Django 3.1.2 on 2021-01-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_booking_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reg_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.car'),
        ),
    ]
