# Generated by Django 3.1.2 on 2021-01-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210112_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dl_num',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
